package io.magictcg.requests

class CardQueryBuilder(
    var id: String? = null,
    var name: String? = null,
    var names: List<String>? = null,
    var manaCost: String? = null,
    var cmc: Int? = null,
    var colors: List<String>? = null,
    var colorIdentity: List<String>? = null,
    var supertypes: String? = null,
    var types: String? = null,
    var subtypes: String? = null,
    var rarity: String? = null,
    var set: String? = null,
    var setName: String? = null,
    var text: String? = null,
    var artist: String? = null,
    var number: String? = null,
    var power: String? = null,
    var toughness: String? = null,
    var loyalty: String? = null,
    var multiverseid: Int? = null,
    var layout: String? = null,
    var legalitiesFormat: String? = null,
    var legalitiesLegality: String? = null,
    var foreignNamesName: String? = null,
    var foreignNamesImageUrl: String? = null,
    var foreignNamesLanguage: String? = null,
    var foreignNamesMultiverseId: Int? = null,
    var page: Int? = null,
    var pageSize: Int? = null

) : QueryBuilder {

    override fun toParams(): Map<String, Any?> = mapOf(
        "id" to id,
        "name" to name,
        "names" to names,
        "manaCost" to manaCost,
        "cmc" to cmc,
        "colors" to colors,
        "colorIdentity" to colorIdentity,
        "supertypes" to supertypes,
        "types" to types,
        "subtypes" to subtypes,
        "rarity" to rarity,
        "set" to set,
        "setName" to setName,
        "text" to text,
        "artist" to artist,
        "number" to number,
        "power" to power,
        "toughness" to toughness,
        "loyalty" to loyalty,
        "multiverseid" to multiverseid,
        "layout" to layout,
        "legalitiesFormat" to legalitiesFormat,
        "legalitiesLegality" to legalitiesLegality,
        "foreignNamesName" to foreignNamesName,
        "foreignNamesImageUrl" to foreignNamesImageUrl,
        "foreignNamesLanguage" to foreignNamesLanguage,
        "foreignNamesMultiverseId" to foreignNamesMultiverseId,
        "page" to page,
        "pageSize" to pageSize
    )
}